version: "3.8"

services:
  web:
    env_file:
      - .env
    build: .
    command: sh -c "make DJ_HOST=${DJANGO_HOST} DJ_PORT=${DJANGO_PORT}"
    volumes:
      - .:/app
    ports:
      - 8000:${DJANGO_PORT}
