version: "3.8"

services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redisdata:/data
  web:
    env_file:
      - .env
    build: .
    command: sh -c "make migrate && make run DJ_PORT=${DJANGO_PORT}"
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/public/static
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    depends_on:
      - web

volumes:
  postgres_data:
  redisdata:
  static_data: