FROM nginxinc/nginx-unprivileged:1-alpine

COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./gunicorn.service /etc/systemd/system/gunicorn_chat.service
COPY ./gunicorn.socket /etc/systemd/system/gunicorn_chat.socket

USER root

RUN mkdir -p /public/static
RUN chmod 755 /public/static

USER nginx